package:
  name: ECRad_conda
  version: {{ version }}

requirements:
    build:
      - make
      - gfortran
      - binutils
      - libblas
      - liblapack
    run:
      - python=3.7
      - numpy
      - scipy
      - matplotlib
      - hdf5
      - netcdf4 >=1.5.6
      - h5py
      - wxpython
      - conda-forge::f90nml>=1.3.1
      - AreWeDreaming::plasma_math_tools
