package: 
  name: ecrad_core
  version: 1.0.0

source:
  git_rev: 1.0.0
  git_url: https://github.com/AreWeDreaming/ECRad_core
requirements:
    build:
      - make
      - gfortran
      - binutils
      - libblas
      - liblapack
    run:
      - python=3.7
      - numpy>=1.21